version: '3'

services:
  web-ui:
    image: web-ui
    build:
      context: WebUI
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on: 
      - api-service
    networks:
      - extranet
    deploy:
      replicas: 1
  history-service:
    image: history-service
    build:
      context: .
      dockerfile: HistoryService/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "81:80"
    networks:
      - intranet
    deploy:
      replicas: 1
  subtract-service:
    image: subtract-service
    build:
      context: .
      dockerfile: SubtractService/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "82:80"
    depends_on:
      - history-service
    networks:
      - intranet
    deploy:
      replicas: 1
  sum-service:
    image: sum-service
    build:
      context: .
      dockerfile: SumService/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "83:80"
    depends_on:
      - history-service
    networks:
      - intranet
    deploy:
      replicas: 1
  api-service:
    image: api-service
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"
    depends_on:
      - sum-service
      - subtract-service
      - history-service
      - zipkin
    networks:
      - intranet
      - extranet
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - extranet
      - intranet
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:5341" # Receive log events over HTTP
      - "5342:80" # Seq web UI (local:redirected)
    networks:
      - extranet
      - intranet
    environment:
      ACCEPT_EULA: Y
    volumes:
      - seq-data:/data

networks:
  intranet:
    external: false
  extranet:
    external: true
volumes:
  seq-data:
