version: '3'

services:
  web-ui:
    image: rootedatnight/dls_assigment:web-ui
#    build:
#      context: WebUI
#      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - extranet
      - intranet
    deploy:
      replicas: 1

  history-service:
    image: rootedatnight/dls_assigment:history-service
#    build:
#      context: .
#      dockerfile: HistoryService/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "81:80"
    depends_on:
      - mssql-service
    networks:
      - intranet
    deploy:
      replicas: 3

  subtract-service:
    image: rootedatnight/dls_assigment:subtract-service
#    build:
#      context: .
#      dockerfile: SubtractService/Dockerfile
    ports:
      - "82:80"
    depends_on:
      - history-service
    networks:
      - intranet
    deploy:
      replicas: 3

  sum-service:
    image: rootedatnight/dls_assigment:sum-service
#    build:
#      context: .
#      dockerfile: SumService/Dockerfile
    ports:
      - "83:80"
    depends_on:
      - history-service
    networks:
      - intranet
    deploy:
      replicas: 3

  api-service:
    image: rootedatnight/dls_assigment:api-service
#    build:
#      context: .
#      dockerfile: API/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - sum-service
      - subtract-service
      - history-service
    networks:
      - intranet
    deploy:
      replicas: 3

  mssql-service:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_SA_PASSWORD: "Password123"
      MSSQL_PID: "Developer"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - intranet

networks:
  intranet:
    external: false
  extranet:
    external: true

volumes:
  mssql-data: